apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: eyal-test-2
configMapGenerator:
- name: eyal-test-2-configmap
  envs:
  - .env
generatorOptions:
  disableNameSuffixHash: true # use a static name
kind: Kustomization
resources:
- deployment.yaml
- service.yaml